CREATE TABLE IF NOT EXISTS hub_subscriptions (
  id TINYINT UNSIGNED NOT NULL,
  updated_at DATETIME(3) NULL,
  subscriptions JSON NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
