package com.igng.tokenmonitor.android.ui.components

import com.igng.tokenmonitor.android.R

/**
 * Generated by `npm run update:fluent-assets`. Do not edit.
 *
 * Tracked-client brand marks, keyed by the same client id every other surface uses.
 * A missing key is *expected* for the handful of marks whose SVG needs a filter, a
 * gradient or a transformed group — those fall back to [ClientBranding.monogram]
 * rather than shipping a mis-converted logo.
 */
object ClientIcons {
  private val drawables: Map<String, Int> = mapOf(
    "amp" to R.drawable.client_amp,
    "augment" to R.drawable.client_augment,
    "cherrystudio" to R.drawable.client_cherrystudio,
    "claude" to R.drawable.client_claude,
    "cline" to R.drawable.client_cline,
    "codebuddy" to R.drawable.client_codebuddy,
    "codebuff" to R.drawable.client_codebuff,
    "codex" to R.drawable.client_codex,
    "cohere" to R.drawable.client_cohere,
    "commandcode" to R.drawable.client_commandcode,
    "copilot" to R.drawable.client_copilot,
    "crush" to R.drawable.client_crush,
    "cursor" to R.drawable.client_cursor,
    "deepseek-harness" to R.drawable.client_deepseek_harness,
    "deepseek" to R.drawable.client_deepseek,
    "devin" to R.drawable.client_devin,
    "doubao" to R.drawable.client_doubao,
    "droid" to R.drawable.client_droid,
    "fx" to R.drawable.client_fx,
    "gemini" to R.drawable.client_gemini,
    "gjc" to R.drawable.client_gjc,
    "goose" to R.drawable.client_goose,
    "grok" to R.drawable.client_grok,
    "hermes-agent" to R.drawable.client_hermes_agent,
    "hindsight" to R.drawable.client_hindsight,
    "jcode" to R.drawable.client_jcode,
    "junie" to R.drawable.client_junie,
    "kilocode" to R.drawable.client_kilocode,
    "kimchi" to R.drawable.client_kimchi,
    "kiro" to R.drawable.client_kiro,
    "lmstudio" to R.drawable.client_lmstudio,
    "meta" to R.drawable.client_meta,
    "minimax" to R.drawable.client_minimax,
    "mistral" to R.drawable.client_mistral,
    "moonshot" to R.drawable.client_moonshot,
    "mux" to R.drawable.client_mux,
    "ollama" to R.drawable.client_ollama,
    "opencode" to R.drawable.client_opencode,
    "opencodereview" to R.drawable.client_opencodereview,
    "openrouter" to R.drawable.client_openrouter,
    "os-apple" to R.drawable.client_os_apple,
    "os-linux" to R.drawable.client_os_linux,
    "os-windows" to R.drawable.client_os_windows,
    "pi" to R.drawable.client_pi,
    "prime-agent" to R.drawable.client_prime_agent,
    "qoder" to R.drawable.client_qoder,
    "qodercn" to R.drawable.client_qodercn,
    "qwen" to R.drawable.client_qwen,
    "reasonix" to R.drawable.client_reasonix,
    "roocode" to R.drawable.client_roocode,
    "sakana" to R.drawable.client_sakana,
    "senpi" to R.drawable.client_senpi,
    "trae" to R.drawable.client_trae,
    "unsloth" to R.drawable.client_unsloth,
    "volcengine" to R.drawable.client_volcengine,
    "warp" to R.drawable.client_warp,
    "workbuddy" to R.drawable.client_workbuddy,
    "xai" to R.drawable.client_xai,
    "xiaomi" to R.drawable.client_xiaomi,
    "zai" to R.drawable.client_zai,
    "zed" to R.drawable.client_zed
  )

  /** 0 when no mark was vendored for this client, i.e. "use the monogram". */
  fun drawable(clientId: String): Int = drawables[clientId] ?: 0
}
