// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit src/shared/<name>.js instead, then run `npm run sync:worker`.

'use strict';

// Limits shared by the Node Hub and the standalone Worker. These values describe
// the existing HTTP/SQL contract; inputs are rejected rather than truncated so a
// long identifier can never silently collide with a valid one.
const MAX_JSON_BODY_BYTES = 1024 * 1024;
const MAX_DEVICE_ID_LENGTH = 191;
const MAX_CLIENT_ID_LENGTH = 100;
const MAX_MODEL_ID_LENGTH = 255;
const MAX_SESSION_ID_LENGTH = 255;
const MAX_PROVIDER_ID_LENGTH = 255;
const MAX_PROJECT_FIELD_LENGTH = 255;
const MAX_MAP_ENTRIES = 16 * 1024;
const MAX_HISTORY_ROWS = 4096;
const MAX_TRACKED_CLIENTS = 256;
const PERIOD_NAMES = ['today', 'month', 'allTime'];
const CLIENT_MAPS = [
  'clients', 'clientCosts', 'clientCacheReads', 'clientCacheWrites', 'clientOutputs',
  'clientUnclassifiedTokens', 'clientModels', 'clientModelCosts'
];
const MODEL_MAPS = [
  'models', 'modelCosts', 'modelCacheReads', 'modelCacheWrites', 'modelOutputs',
  'modelUnclassifiedTokens'
];

function own(object, key) {
  return Object.prototype.hasOwnProperty.call(object || {}, key);
}

function firstTruthy(...values) {
  return values.find((value) => Boolean(value));
}

function validationError(code, message, details = {}) {
  const error = new Error(message);
  error.code = code;
  Object.assign(error, details);
  return error;
}

function ensureLength(value, maxLength, field) {
  if (value === undefined || value === null || value === '') return;
  if (String(value).length > maxLength) {
    throw validationError(
      'field_too_long',
      `${field} exceeds the maximum length of ${maxLength}`,
      { field, maxLength }
    );
  }
}

function ensureObject(value, field) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  if (Object.keys(value).length > MAX_MAP_ENTRIES) {
    throw validationError(
      'too_many_entries',
      `${field} contains too many entries`,
      { field, maxEntries: MAX_MAP_ENTRIES }
    );
  }
  return true;
}

function ensureMapKeys(value, maxLength, field) {
  if (!ensureObject(value, field)) return;
  for (const key of Object.keys(value)) ensureLength(key, maxLength, `${field} key`);
}

function ensureNestedMap(value, outerMaxLength, innerMaxLength, field) {
  if (!ensureObject(value, field)) return;
  for (const [outerKey, inner] of Object.entries(value)) {
    ensureLength(outerKey, outerMaxLength, `${field} client key`);
    ensureMapKeys(inner, innerMaxLength, `${field}[client]`);
  }
}

function sessionIdFromInput(session) {
  return firstTruthy(
    session?.sessionId,
    session?.session_id,
    session?.session,
    session?.conversationId,
    session?.conversation_id,
    session?.threadId,
    session?.thread_id
  );
}

function clientFromInput(session) {
  return firstTruthy(
    session?.client,
    session?.source,
    session?.platform,
    session?.agent,
    session?.tool
  );
}

function ensureSessionMap(value, field) {
  if (!ensureObject(value, field)) return;
  for (const [fallbackKey, session] of Object.entries(value)) {
    if (!session || typeof session !== 'object' || Array.isArray(session)) continue;
    ensureLength(clientFromInput(session), MAX_CLIENT_ID_LENGTH, `${field} client`);
    const sessionId = sessionIdFromInput(session);
    ensureLength(sessionId || fallbackKey, MAX_SESSION_ID_LENGTH, `${field} session id`);
    ensureLength(
      firstTruthy(session.projectId, session.project_id),
      MAX_PROJECT_FIELD_LENGTH,
      `${field} project id`
    );
    ensureLength(
      firstTruthy(session.projectLabel, session.project_label),
      MAX_PROJECT_FIELD_LENGTH,
      `${field} project label`
    );
    ensureMapKeys(session.models, MAX_MODEL_ID_LENGTH, `${field} models`);
    ensureMapKeys(session.modelCosts, MAX_MODEL_ID_LENGTH, `${field} model costs`);
    ensureMapKeys(session.providers, MAX_PROVIDER_ID_LENGTH, `${field} providers`);
  }
}

function ensureProjects(value, field) {
  if (!ensureObject(value, field)) return;
  for (const [key, project] of Object.entries(value)) {
    ensureLength(key, MAX_PROJECT_FIELD_LENGTH, `${field} key`);
    if (!project || typeof project !== 'object' || Array.isArray(project)) continue;
    ensureLength(project.label, MAX_PROJECT_FIELD_LENGTH, `${field} label`);
    ensureMapKeys(project.clients, MAX_CLIENT_ID_LENGTH, `${field} clients`);
  }
}

function ensurePeriod(period, field) {
  if (!ensureObject(period, field)) return;
  for (const mapName of CLIENT_MAPS) {
    if (mapName === 'clientModels' || mapName === 'clientModelCosts') {
      ensureNestedMap(period[mapName], MAX_CLIENT_ID_LENGTH, MAX_MODEL_ID_LENGTH, `${field}.${mapName}`);
    } else {
      ensureMapKeys(period[mapName], MAX_CLIENT_ID_LENGTH, `${field}.${mapName}`);
    }
  }
  for (const mapName of MODEL_MAPS) ensureMapKeys(period[mapName], MAX_MODEL_ID_LENGTH, `${field}.${mapName}`);
  ensureSessionMap(period.sessions, `${field}.sessions`);
  ensureProjects(period.projects, `${field}.projects`);
}

function ensureHistory(history) {
  if (!history || typeof history !== 'object' || Array.isArray(history)) return;
  for (const name of ['daily', 'monthly']) {
    const rows = history[name];
    if (!Array.isArray(rows)) continue;
    if (rows.length > MAX_HISTORY_ROWS) {
      throw validationError('too_many_entries', `history.${name} contains too many rows`, {
        field: `history.${name}`,
        maxEntries: MAX_HISTORY_ROWS
      });
    }
    for (const row of rows) {
      if (!row || typeof row !== 'object' || Array.isArray(row)) continue;
      ensureMapKeys(row.perClient, MAX_CLIENT_ID_LENGTH, `history.${name}.perClient`);
      ensureMapKeys(row.perModel, MAX_MODEL_ID_LENGTH, `history.${name}.perModel`);
    }
  }
}

function validateDeviceRecordPayload(record) {
  if (!record || typeof record !== 'object' || Array.isArray(record)) {
    throw validationError('invalid_payload', 'device record must be an object');
  }

  ensureLength(firstTruthy(record.deviceId, record.id), MAX_DEVICE_ID_LENGTH, 'deviceId');
  ensureLength(record.hostname, MAX_PROJECT_FIELD_LENGTH, 'hostname');
  ensureLength(record.platform, MAX_PROJECT_FIELD_LENGTH, 'platform');
  ensureLength(record.agentVersion, MAX_PROJECT_FIELD_LENGTH, 'agentVersion');
  ensureLength(record.agentRuntime, MAX_PROJECT_FIELD_LENGTH, 'agentRuntime');

  if (Array.isArray(record.trackedClients)) {
    if (record.trackedClients.length > MAX_TRACKED_CLIENTS) {
      throw validationError('too_many_entries', 'trackedClients contains too many entries', {
        field: 'trackedClients',
        maxEntries: MAX_TRACKED_CLIENTS
      });
    }
    for (const client of record.trackedClients) ensureLength(client, MAX_CLIENT_ID_LENGTH, 'trackedClients entry');
  } else {
    ensureLength(record.trackedClients, MAX_TRACKED_CLIENTS * (MAX_CLIENT_ID_LENGTH + 1), 'trackedClients');
  }
  ensureMapKeys(record.clientStatus, MAX_CLIENT_ID_LENGTH, 'clientStatus');
  ensureHistory(record.history);

  const periods = record.periods && typeof record.periods === 'object' && !Array.isArray(record.periods)
    ? record.periods
    : null;
  for (const periodName of PERIOD_NAMES) {
    const period = firstTruthy(record[periodName], periods && own(periods, periodName) ? periods[periodName] : null);
    ensurePeriod(period, periodName);
  }
  return true;
}

module.exports = {
  MAX_CLIENT_ID_LENGTH,
  MAX_DEVICE_ID_LENGTH,
  MAX_HISTORY_ROWS,
  MAX_JSON_BODY_BYTES,
  MAX_MAP_ENTRIES,
  MAX_MODEL_ID_LENGTH,
  MAX_PROJECT_FIELD_LENGTH,
  MAX_PROVIDER_ID_LENGTH,
  MAX_SESSION_ID_LENGTH,
  MAX_TRACKED_CLIENTS,
  PERIOD_NAMES,
  validateDeviceRecordPayload
};
